const path = require('path');
const fs = require('fs');

module.exports = {
  options: async (tln, args) => {},
  env: async (tln, env) => {
    env.TLN_UID = 'sh.tln';

    env.TLN_VERSION = fs.readFileSync(path.join(__dirname, 'version'), 'utf8').trim();
    env.KUBECONFIG = path.join(__dirname, 'secrets', '.kube.config');
    env.DOCKER_CONFIG = path.join(__dirname, 'secrets');

    env.TLN_DOCKER_REGISTRY = env.TLN_SH_REGISTRY = 'registry.digitalocean.com/projects-cr';

    env.TLN_SH_NAMESPACE = 'tln-sh';
    env.TLN_SH_SECRETS = path.join(__dirname, 'secrets', 'values.yaml');
  },
  dotenvs: async (tln) => [],
  inherits: async (tln) => [],
  depends: async (tln) => [],
  steps: async (tln) => [
    { id: 'create-secrets', builder: async (tln, script) => {
        const crt = path.join(__dirname, 'secrets', 'tln.sh.crt');
        const key = path.join(__dirname, 'secrets', 'tln.sh.key');
        const config = path.join(__dirname, 'secrets', 'config.json');
        const secrets = path.join(__dirname, 'secrets', 'values.yaml');

        script.set([`
echo "tlsCertificate: |" > ${secrets} && cat ${crt} | sed 's/^/  /' >> ${secrets} && \\
echo "tlsKey: |" >> ${secrets} && cat ${key} | sed 's/^/  /' >> ${secrets} && \\
echo "dockerSecret: |" >> ${secrets} && cat ${config} | sed 's/^/  /' >> ${secrets}
        `]);
      }
    },
  ],
  components: async (tln) => []
}