
module.exports = {
  options: async (tln, args) => {},
  env: async (tln, env) => {
    env.TLN_ATLS_NAMESPACE = 'tln-sh';
    env.TLN_ATLS_K8S_CONFIG = 'k8s-all.yml';
  },
  dotenvs: async (tln) => [],
  inherits: async (tln) => [],
  depends: async (tln) => [],
  steps: async (tln) => [],
  components: async (tln) => []
}