const path = require('path');

module.exports = {
  options: async (tln, args) => {},
  env: async (tln, env) => {

  },
  dotenvs: async (tln) => [],
  inherits: async (tln) => [],
  depends: async (tln) => ['kubectl-1.21.4', 'helm-3.6.3'],
  steps: async (tln) => [
    { id: 'deploy', builder: async (tln, script) => {
        script.set([`
helm install tln-sh ${path.join(__dirname, 'helm', 'tln-sh')} \\
--set namespace=${script.env.TLN_SH_NAMESPACE} \\
--set registry=${script.env.TLN_SH_REGISTRY} \\
--set domain=tln.sh \\
--set reverseDomain=sh.tln \\
--set tlnShVersion=${script.env.TLN_VERSION} \\
--values ${script.env.TLN_SH_SECRETS}
        `]);
      }
    },
    { id: 'ingress-status', builder: async (tln, script) => {
        script.set([`
kubectl --namespace ingress-basic get services -o wide  nginx-ingress-ingress-nginx-controller
        `]);
      }
    },
    { id: 'cluster-status', builder: async (tln, script) => {
        script.set([`
kubectl get all -n ${script.env.TLN_SH_NAMESPACE}
        `]);
      }
    },
    { id: 'status', builder: ['ingress-status', 'cluster-status']
    },

    { id: 'undeploy', builder: async (tln, script) => {
        script.set([`
helm uninstall tln-sh
        `]);
      }
    }

  ],
  components: async (tln) => []
}