apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-html
spec:
  replicas: 3
  selector:
    matchLabels:
      component: static.html
  template:
    metadata:
      labels:
        component: static.html
    spec:
      restartPolicy: Always
      containers:
      - name: static-html
        image: atls/sh.tln.static.html:20.8.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-static-html
spec:
  selector:
    component: static.html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`tln.sh`)
    services:
    - name: service-static-html
      port: 80
