{{- range .Values.routes }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tln-sh-ingress-{{ .suffix }}
  namespace: {{ $.Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ $.Values.proxyBodySize }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: {{ .rewrite }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - 'tln.sh'
    secretName: ingress-tls
  rules:
  - host: "tln.sh"
    http:
      paths:
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .backend }}
            port:
              number: 80
        
---
{{- end }}
